#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
feh --bg-fill /home/oops/Pictures/wallpaper.png &
~/.config/polybar/launch.sh --cuts &
vmware-user &

bspc config pointer_modifier mod1

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor Virtual1 -d 1 2 3 4 5
bspc monitor Virtual2 -d 6 7 8  9 0

bspc config border_width         	1
bspc config window_gap           	12
bspc config normal_border_color		"#141C21"
bspc config focused_border_color	"#EBDBB2"
bspc config presel_feedback_color	"#EBDBB2"
bspc config click_to_focus				true

bspc config split_ratio          0.30
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
